##### NAME: JANMEJAY MOHANTY <br> COURSE: CS 556 B <br> COURSE NAME: MATHEMATICAL FOUNDATIONS OF MACHINE LEARNING <br> CWID: 20009315 <br> EMAIL: JMOHANTY@STEVENS.EDU <br> PROGRAM: SVD

In [76]:
import numpy as np   # Importing libraries

In [77]:
u = np.load('U.npy')
s = np.load('S.npy')
s = np.diag(s)
vt = np.load('V_transpose.npy')
v = np.transpose(vt)

print("U =\n {}\n\nS =\n {}\n\nV =\n {}\n\nVT =\n {}".format(u,s,v,vt))

U =
 [[-0.42344517  0.55665609 -0.24102467  0.3305458  -0.24562245]
 [-0.50699337 -0.47790996 -0.16495257  0.37953185  0.58331032]
 [-0.37335489  0.50609813 -0.19182881 -0.4734306   0.385749  ]
 [-0.34447683  0.12820357  0.63388605  0.41223622 -0.23721861]
 [-0.42422527 -0.40791144 -0.38601146 -0.2525886  -0.62705737]
 [-0.35443853 -0.15090679  0.57191179 -0.53741866  0.033805  ]]

S =
 [[13.2663997   0.          0.          0.          0.        ]
 [ 0.          7.31094493  0.          0.          0.        ]
 [ 0.          0.          4.68971622  0.          0.        ]
 [ 0.          0.          0.          0.89013458  0.        ]
 [ 0.          0.          0.          0.          0.51666749]]

V =
 [[-0.43399074  0.55963405 -0.07820851  0.42591506 -0.55762134]
 [-0.40613677  0.53864051 -0.20812855 -0.48880552  0.51251438]
 [-0.42465386 -0.08782676  0.89447713 -0.01119466  0.10835544]
 [-0.46105389 -0.38001516 -0.30501222  0.57946426  0.46282448]
 [-0.50378901 -0.49452105 -0.2396750

## Strength of concept 1 in the SVD Decomposition

In [78]:
print("The Strength of concept 1 in SVD decomposition: ", round(s[0][0],2))

The Strength of concept 1 in SVD decomposition:  13.27


### The computing missing rating for Movie 5 (Casablanca) across all users in the system

In [79]:
us = np.matmul(u[2],s)
#print(us)
#print(vt[:,4])
Cu3 = usvt = round(np.matmul(us,vt[:,4]),2)
print("R(User3, Casablanca) = UUser1.S.VT = ", Cu3)

R(User3, Casablanca) = UUser1.S.VT =  1.0


In [80]:
us = np.matmul(u[3],s)
#print(us)
#print(vt[:,4])
Cu4 = usvt = round(np.matmul(us,vt[:,4]),2)
print("R(User4, Casablanca) = UUser1.S.VT = ", Cu4)

R(User4, Casablanca) = UUser1.S.VT =  1.0


In [81]:
us = np.matmul(u[5],s)
#print(us)
#print(vt[:,4])
Cu6 = usvt = round(np.matmul(us,vt[:,4]),2)
print("R(User6, Casablanca) = UUser1.S.VT = ", Cu6)

R(User6, Casablanca) = UUser1.S.VT =  2.5


### The computing missing rating for Movie 4 (Amelie) across all users in the system

In [82]:
us = np.matmul(u[0],s)
#print(us)
#print(vt[:,3])
Au1 = usvt = round(np.matmul(us,vt[:,3]),2)
print("R(User1, Amelie) = UUser1.S.VT = ", Au1)


R(User1, Amelie) = UUser1.S.VT =  1.5


In [83]:
us = np.matmul(u[2],s)
#print(us)
#print(vt[:,3])
Au3 = usvt = round(np.matmul(us,vt[:,3]),2)
print("R(User3, Amelie) = UUser1.S.VT = ", Au3)

R(User3, Amelie) = UUser1.S.VT =  1.0


In [84]:
us = np.matmul(u[3],s)
#print(us)
#print(vt[:,3])
Au4 = usvt = round(np.matmul(us,vt[:,3]),2)
print("R(User4, Amelie) = UUser1.S.VT = ", Au4)

R(User4, Amelie) = UUser1.S.VT =  1.0


In [85]:
us = np.matmul(u[5],s)
#print(us)
#print(vt[:,3])
Au6 = usvt = round(np.matmul(us,vt[:,3]),2)
print("R(User6, Amelie) = UUser1.S.VT = ", Au6)

R(User6, Amelie) = UUser1.S.VT =  1.5


### The computing missing rating for Movie 3 (Harry Potter) across all users in the system

In [86]:
us = np.matmul(u[0],s)
#print(us)
#print(vt[:,2])
Hu1 = usvt = round(np.matmul(us,vt[:,2]),2)
print("R(User1, Harry Potter) = UUser1.S.VT = ", Hu1)

R(User1, Harry Potter) = UUser1.S.VT =  1.0


In [87]:
us = np.matmul(u[2],s)
#print(us)
#print(vt[:,2])
Hu3 = usvt = round(np.matmul(us,vt[:,2]),2)
print("R(User3, Harry Potter) = UUser1.S.VT = ", Hu3)

R(User3, Harry Potter) = UUser1.S.VT =  1.0


In [88]:
us = np.matmul(u[4],s)
#print(us)
#print(vt[:,2])
Hu5 = usvt = round(np.matmul(us,vt[:,2]),2)
print("R(User5, Harry Potter) = UUser1.S.VT = ", Hu5)

R(User5, Harry Potter) = UUser1.S.VT =  1.0


### The computing missing rating for Movie 2 (Top Gun) across all users in the system

In [89]:
us = np.matmul(u[1],s)
#print(us)
#print(vt[:,1])
Tu2 = usvt = round(np.matmul(us,vt[:,1]),2)
print("R(User2, Top Gun) = UUser1.S.VT = ", Tu2)

R(User2, Top Gun) = UUser1.S.VT =  1.0


In [90]:
us = np.matmul(u[4],s)
#print(us)
#print(vt[:,1])
Tu5 = usvt = round(np.matmul(us,vt[:,1]),2)
print("R(User5, Top Gun) = UUser1.S.VT = ", Tu5)

R(User5, Top Gun) = UUser1.S.VT =  1.0


In [91]:
us = np.matmul(u[5],s)
#print(us)
#print(vt[:,1])
Tu6 = usvt = round(np.matmul(us,vt[:,1]),2)
print("R(User6, Top Gun) = UUser1.S.VT = ", Tu6)

R(User6, Top Gun) = UUser1.S.VT =  1.0


### The computing missing rating for Movie 1 (Rambo) across all users in the system

In [92]:
us = np.matmul(u[1],s)
#print(us)
#print(vt[:,0])
Ru2 = usvt = round(np.matmul(us,vt[:,0]),2)
print("R(User2, Rambo) = UUser1.S.VT = ", Ru2)

R(User2, Rambo) = UUser1.S.VT =  1.0


In [93]:
us = np.matmul(u[3],s)
#print(us)
#print(vt[:,0])
Ru4 = usvt = round(np.matmul(us,vt[:,0]),2)
print("R(User4, Rambo) = UUser1.S.VT = ", Ru4)

R(User4, Rambo) = UUser1.S.VT =  2.5


In [94]:
us = np.matmul(u[5],s)
#print(us)
#print(vt[:,0])
Ru6 = usvt = round(np.matmul(us,vt[:,0]),2)
print("R(User2, Rambo) = UUser1.S.VT = ", Ru6)

R(User2, Rambo) = UUser1.S.VT =  1.0


In [95]:
rating = np.matrix([[5.0 ,4.5,Hu1,Au1,1.0],[Ru2,Tu2,2.5,5.0,5.0],[4.0,4.5,Hu3,Au3,Cu3],[Ru4,1.5,4.5,Au4,Cu4],[1.0,Tu5,Hu5,4.0,5.0],[Ru6,Tu6,4.5,Au6,Cu6]])
print("Rating Matrix =\n {}".format(rating))

Rating Matrix =
 [[5.  4.5 1.  1.5 1. ]
 [1.  1.  2.5 5.  5. ]
 [4.  4.5 1.  1.  1. ]
 [2.5 1.5 4.5 1.  1. ]
 [1.  1.  1.  4.  5. ]
 [1.  1.  4.5 1.5 2.5]]


In [96]:
avg = np.mean(rating, axis=0)
print(avg)

[[2.41666667 2.25       2.41666667 2.33333333 2.58333333]]


### The average rating for Movie 3 (Harry Potter) across all users in the system

In [97]:
H_avg = avg[:,2]
print("Average rating of Harry Potter: ", H_avg)

Average rating of Harry Potter:  [[2.41666667]]


In [98]:
def ohr(x,average):     # Function defined for finding out overall highest rating
    if x == 0: 
        print("Rambo has overall highest rating: ",average)
    elif x == 1: 
        print("Top-Gun has overall highest rating: ",average)  
    elif x == 2: 
        print("Harry Potter has overall highest rating: ",average) 
    elif x == 3: 
        print("Amelie has overall highest rating: ",average)  
    else: 
        print("Casablanca has overall highest rating: ",average)              

In [99]:
m = np.max(avg)
result = np.where(avg == np.max(avg))
loc = result[1]
ohr(loc,m)

Casablanca has overall highest rating:  2.5833333333333335
